config/routes.rb
Rails.application.routes.draw do
  root to: 'tasks#index'

  resources :tasks do
    resources :status, only: [:update]
    resources :comments, only: [:create]
  end

  resources :users, only: [:new, :create, :show]
  
  get   '/login'  => 'sessions#new', as: 'new_login'
  post  '/login'  => 'sessions#create'
  delete'/logout' => 'sessions#destroy'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :task
end

app/models/task.rb
class Task < ApplicationRecord
  belongs_to :user, foreign_key: "assignee_id"
  has_many :comments, dependent: :destroy
  
  validates  :description, presence: true
  validates  :creator_id, presence: true
  validates  :assignee_id, presence: true

  enum state: ["open", "in_progress", "done"]
end

app/models/user.rb
class User < ApplicationRecord
  has_many :tasks, dependent: :destroy, foreign_key: "assignee_id" 
  has_many :comments, dependent: :destroy

  has_secure_password
  
  validates :email, presence: true, uniqueness: true
  validates :name, presence: true, uniqueness: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include Pundit
  include SessionsHelper

  rescue_from Pundit::NotAuthorizedError, with: :user_not_authorized

  private
    def require_login
      unless logged_in?
        flash[:danger] = "Please Log In to view the Tasks."
        redirect_to new_login_path
      end
    end

    def logged_in?
      !current_user.nil?
    end
  
    def current_user
      if session[:user_id]
        @current_user ||= User.find(session[:user_id])
      end
    end

    def user_not_authorized
      flash[:warning] = "All accesssable tasks are listed below."
      redirect_to root_path
    end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :current_user
  before_action :fetch_task

  def create
    @comment = @task.comments.create(comment_params)
    @comment.user_id = current_user.id
    if @comment.save
      redirect_to @task
    end
  end

  private
    def fetch_task
      @task = Task.find(params[:task_id])
    end

    def comment_params
      params.require(:comment).permit(:content)
    end 
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
	def new
  end

	def create
		user = User.find_by(email: params[:login][:email].downcase)

	# If user exist in DB run has_secure_password's .authenticate()
		if user && user.authenticate(params[:login][:password]) 
		  # Save the user.id in session cookie if password correct:
		  session[:user_id] = user.id
		  flash[:notice] = 'Successfully logged in!'
		  redirect_to root_path 
		else
		  # if email or password incorrect, re-render login page:
		  flash.now[:alert] = 'Incorrect credentials, try again.'
		  render :new
		end
	end

	def destroy
	  # remove saved user_id from the cookie:
	  session.delete(:user_id)
	  flash[:notice] = 'Logged out!'
	  redirect_to login_path 
  end
end

app/controllers/status_controller.rb
class StatusController < ApplicationController
  
  def update
    @task = Task.find(params[:id])
		@task.state = params[:state]
		if @task.save
			respond_to do |format|
				format.js { render 'update' }
			end
		end
  end
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  before_action :require_login
  skip_before_action :verify_authenticity_token, :only => [:update_state, :update]

  def index
    @tasks = policy_scope(Task)
  end

  def new
    @task = Task.new
  end

  def create
    @user = User.find(task_params[:assignee_id])
    @task = @user.tasks.new(task_params)
    authorize @task
    @task.creator_id = current_user.id
    
    if @task.valid?
      @task.save
      redirect_to task_url(@task)
    else
      render new
    end
  end

  def show
    @task = Task.find(params[:id])
    authorize @task
    @comments = @task.comments
  end

  def edit
    @task = Task.find(params[:id])
    authorize @task
  end

  def update
    @task = Task.find(params[:id])
    authorize @task

    if @task.update_attributes(task_params)
    redirect_to @task
    end
  end

  def destroy
    @task = Task.find(params[:id])
    authorize @task
    @task.destroy
    redirect_to tasks_url
  end

  private 

    def task_params
      params.require(:task).permit(:description, :assignee_id)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
	
	def index
		@users = User.all
	end

	def new
		@user = User.new
	end

	def create
		@user = User.new(user_params)
		if @user.valid?
			@user.save
			session[:user_id] = @user.id.to_s
			flash[:notice] = 'Account created successfully!'
			redirect_to root_url
		else
			flash.now[:alert] = @user.errors.full_messages.join(', ')
			render new_user_path
		end
	end
	
	def destroy
		user = User.find(params[:id])

		user.destroy
		@users = User.all
		redirect_to users_url
	end

	private 

		def user_params
			params.require(:user).permit(:name, :email, :password, :password_confirmation)
		end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
  def logged_in?
    !current_user.nil?
  end

  def current_user
    if session[:user_id]
      @current_user ||= User.find(session[:user_id])
    end
  end
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/comments/_form.html.erb
<%= form_for ([@task, @task.comments.new]) do |f| %>
  <br>
  <%= f.label :content, "Add Comment" %>
  <br>
  <%= f.text_area :content %>
  <br>
  <%= f.submit "Submit" %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Taskmanager</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <% flash.each do |key, value| %>
      <div class="alert alert-<%= key %>"><%= value %></div>
    <% end %>
    <div id = "container">
      <% if current_user %>
        Hi <%= current_user.name %>
        <br>
        <%= link_to "Logout", logout_path, method: :delete %>
      <% end %>
      <%= yield %>
    </div>
  </body>
</html>

app/views/status/update.js.erb
$('#state').html("<strong><%= @task.state %><strong>");

app/views/tasks/edit.html.erb
<div>
  <h3>Enter New Details.</h3>
  
  <%= form_for(@task) do |f| %>

    <%= f.label :description %>
    <%= f.text_field :description %> 
    
    <%= f.submit "Update Task"%>
  <% end %>
</div>

app/views/tasks/index.html.erb
<div>
	<%= link_to 'Add new task', new_task_path %>

	<h1>Tasks List</h1>
	<% if @tasks.blank? %>
		<p>You have not created or have been assigned to a Task</p>
	<% else %>
		<% @tasks.each do |task| %>
			<%= link_to "#{task.description}", task_path(task) %>
			<%= button_to  "Edit", edit_task_path(task), method: :get %>
			<%= button_to  "Delete", task, method: :delete %></br>
		<% end %>
	<% end %>
</div>

app/views/tasks/new.html.erb
<div>
	<% if @task.errors.any? %>
		<ul>
			<% @task.errors.full_messages.each do |msg| %>
			<li><%= msg %></li>
			<% end %>
		</ul>
	<% end %>

	<h3>Add new Task</h3>
		<%= form_for(@task) do |f| %>
			<%= f.label :description %>
			<%= f.text_field :description %>
			<%= collection_select(:task, :assignee_id, User.all, :id, :name) %>
			<%= f.submit "Create Task"%>
		<% end %>
</div>

app/views/tasks/show.html.erb
<div>
	<div>
		<h2> Here are your task details! </h2>
		<h3> 
			<%= @task.id %>)
			<%= @task.description %>
		</h3>
	</div>
	
	<div>
		Current Task State : 
		<span id="state">
			<strong><%= @task.state %></strong>
		</span>
		<br>
		<br>
		Change the state of Task:
		<%= button_to "open", task_status_url({task_id: @task.id, state: "open" }), remote: true, date:{type: 'script'}, method: :patch%>
		<%= button_to "in progress", task_status_url({task_id: @task.id, state: "in_progress" }), remote: true, date:{type: 'script'}, method: :patch%>
		<%= button_to "Done", task_status_url({task_id: @task.id, state: "done" }), remote: true, date:{type: 'script'}, method: :patch%>

		<%= link_to 'Edit', edit_task_path(@task) %>
		<%= link_to 'Back', root_path %>
	</div>

	<br>
	<br>

	<div>
		<h2><strong>Comments</strong></h2>3
		<% @comments.each do |comment| %>
				<p>
					<h3>
						<%= comment.content %>
					</h3>
					<%= time_ago_in_words(comment.created_at) %><span> ago</span>
				</p>
				<br>
		<% end %>
		<%= render 'comments/form' %>
  </div>
</div>

app/views/tasks/update_state.js.erb
$('#state').html("<strong><%= @task.state %><strong>");

app/views/users/index.html.erb
<%= link_to 'Add new user', new_user_url %>

<h1>users List</h1>
<% @users.each do |user| %>
  <%= user.id %>
	<%= user.name %>
	<%= button_to  "Delete", user , :method => :delete %></br>
<% end %>

app/views/users/new.html.erb
<h1>Sign Up</h1>

<%= form_for @user do |f| %>
  <div>
    <%= f.label :name %>
    <%= f.text_field :name, autofocus: true %>
  </div>
  <div>
    <%= f.label :email %>
    <%= f.text_field :email %>
  </div>

  <div>
    <%= f.label :password %>
    <%= f.password_field :password %>
  </div>
  <div>
    <%= f.label :password_confirmation %>
    <%= f.password_field :password_confirmation %>
  </div>
  <div>
    <%= f.submit "Sign up!" %>
  </div>
<% end %>